# Generated by Django 2.1.7 on 2019-03-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_code', models.IntegerField()),
                ('product_description', models.TextField()),
                ('product_image', models.CharField(max_length=1000)),
            ],
        ),
    ]
